import React from 'react';
import { Heart, Play } from 'lucide-react';
import { Countdown, MusicButton, Reveal, RsvpForm, VenueLink, WeddingCalendar, useInvitationPage } from './NewInvitationCommon.jsx';
import './template64New.css';
import './auditFidelity.css';

const a = '/assets/new-templates/thiep-cuoi-64';

export default function Template64New() {
  const count = useInvitationPage('template64new-page', '2027-11-30T11:00:00+07:00');
  return <main className="new-invitation-page t64n">
    <MusicButton className="t64n-music" />
    <section className="t64n-player"><Reveal className="t64n-playerHead" direction="down"><h1>Thiệp mời đám cưới!</h1><div><p>Anh Dũng<br /><i>&amp;</i> Minh Trang</p><time>2027-11-30 20:07</time></div></Reveal><Reveal className="t64n-track" direction="right"><div><small>Marry You!</small><p>Bài hát đã được phát cho bạn nghe.</p></div><img src={`${a}/image-4.webp`} alt="Anh Dũng và Minh Trang" /><button type="button" aria-label="Phát bài hát"><Play fill="currentColor" /></button></Reveal><Reveal className="t64n-calligraphy"><img src={`${a}/image-3.webp`} alt="Wedding invitation" /><small>W E D D I N G&nbsp;&nbsp; I N V I T A T I O N</small></Reveal><Reveal as="img" className="t64n-feature" src={`${a}/image-4.webp`} alt="Anh Dũng và Minh Trang ngoài trời" direction="up" /></section>
    <section className="t64n-moon"><Reveal as="h2">Mặt trăng lúc mới sinh</Reveal><div><Reveal direction="right"><img src={`${a}/image-1.webp`} alt="Mặt trăng ngày sinh Anh Dũng" /><small>25 · 05 · 2000</small><b>Anh Dũng</b></Reveal><Reveal direction="left"><img src={`${a}/image-2.webp`} alt="Mặt trăng ngày sinh Minh Trang" /><small>27 · 11 · 2005</small><b>Minh Trang</b></Reveal></div><Reveal as="p">May mắn ngẫu nhiên trong vũ trụ<br />đã đưa hai chúng mình đến gần nhau.</Reveal></section>
    <section className="t64n-story"><Reveal as="h2">Our love story</Reveal><div><Reveal><b>01</b><img src={`${a}/image-5.webp`} alt="Lần đầu gặp nhau" /><h3>Tình yêu sét đánh</h3><p>Đó là lúc mình nhận ra bạn. Cậu ấy có nụ cười chân thành nhất và trái tim nhân hậu nhất.</p></Reveal><Reveal><b>02</b><img src={`${a}/image-6.webp`} alt="Chuyện tình Anh Dũng và Minh Trang" /><h3>Đi cùng nhau</h3><p>Từ một cuộc gặp gỡ tình cờ, chúng mình chọn trở thành người bạn đồng hành không thể tách rời.</p></Reveal></div></section>
    <section className="t64n-film"><Reveal className="t64n-filmIntro"><small>OUR WEDDING FILM</small><h2>我们的婚纱照</h2><p>Giữa một khu vườn yên tĩnh, chúng mình giữ lại những ngày bình thường bằng những khung hình thật dịu dàng.</p></Reveal><Reveal as="img" className="t64n-filmHero" src={`${a}/image-4.webp`} alt="Anh Dũng và Minh Trang trong khu vườn" direction="up" /><div className="t64n-filmGrid"><Reveal as="img" src={`${a}/image-5.webp`} alt="Album cưới trong khu vườn" direction="right" /><Reveal as="img" src={`${a}/image-6.webp`} alt="Khoảnh khắc bên nhau" direction="left" /><Reveal as="img" src={`${a}/image-4.webp`} alt="Một ngày bên nhau" direction="right" /><Reveal as="img" src={`${a}/image-5.webp`} alt="Chuyện tình giản dị" direction="left" /></div><Reveal as="p" className="t64n-filmEssay">Dù thế giới bên ngoài có hỗn loạn đến đâu, chúng mình vẫn mong luôn gắn bó theo cách giản dị nhất: gia đình quây quần, ánh sáng ấm áp của ngọn đèn và thời gian bên những người mình yêu thương.</Reveal><Reveal as="img" className="t64n-filmWide" src={`${a}/image-6.webp`} alt="Album Anh Dũng và Minh Trang" direction="scale" /><Reveal className="t64n-filmOutro"><h2>婚礼邀请函</h2><p>Tôi trao cho em cả tâm hồn mình, cùng những tính khí kỳ quặc của nó. Nó chỉ có một phẩm chất tốt đẹp duy nhất: nó yêu em.</p></Reveal></section>
    <section className="t64n-letter"><Reveal direction="right"><small>A LETTER FOR YOU</small><h2>Cuộc sống chỉ cần hai điều may mắn</h2><p>Gặp được anh và ở bên nhau đến cuối đời. Giờ đây, chúng ta quyết định bắt đầu một chương mới, để tình yêu tiếp tục với tư cách vợ chồng.</p></Reveal><Reveal as="img" src={`${a}/image-4.webp`} alt="Chuyện tình trong khu vườn" direction="left" /></section>
    <section className="t64n-promise"><Reveal as="img" src={`${a}/image-5.webp`} alt="Minh Trang trong ngày cưới" direction="right" /><Reveal><h2>Love is<br />our universe</h2><p>Dù thế giới bên ngoài có hỗn loạn đến đâu, chúng mình vẫn mong luôn gắn bó theo cách giản dị nhất: gia đình quây quần, ánh sáng ấm áp và một người luôn ở cạnh bên.</p></Reveal><Reveal as="img" src={`${a}/image-6.webp`} alt="Anh Dũng và Minh Trang" direction="left" /></section>
    <section className="t64n-invitation"><Reveal><small>30 THÁNG 11 NĂM 2027</small><h2>Dũng <i>&amp;</i> Trang</h2><p>Chúng tôi chân thành mời những người thân yêu và bạn bè thân thiết đến chứng kiến tình yêu và sẻ chia niềm vui này.</p></Reveal><Countdown values={count} className="t64n-inviteCount" /></section>
    <section className="t64n-day"><WeddingCalendar month="NOVEMBER · 2027" weddingDay={30} offset={0} /><Countdown values={count} className="t64n-count" /><Reveal><p>11:00 · Thứ Ba<br />CineLove Wedding Hall, Hà Nội</p><VenueLink query="Cinelove Hanoi">Xem chỉ đường</VenueLink></Reveal></section>
    <section className="t64n-end"><Heart fill="currentColor" /><RsvpForm accent="#181818" className="t64n-rsvp" /><Reveal as="h2">Endless playlist, endless love.</Reveal></section>
    <section className="t64n-finalQuote"><Reveal as="p">Tôi trao cho em cả tâm hồn mình,<br />cùng những tính khí kỳ quặc của nó.<br />Nó chỉ có một phẩm chất tốt đẹp duy nhất:<br /><b>nó yêu em.</b></Reveal><Countdown values={count} className="t64n-finalCount" /><Reveal as="img" src={`${a}/image-3.webp`} alt="Save the date" /></section>
  </main>;
}
